package com.example.patientsportal.db.arrays

import com.example.patientsportal.db.arrays.ArrayDoctors.arrayDoctors
import com.example.patientsportal.db.arrays.ArrayPatients.arrayPatients
import com.example.patientsportal.db.arrays.ArrayPlaces.arrayPlaces
import com.example.patientsportal.db.arrays.ArraySpecialities.arraySpecialities
import com.example.patientsportal.entities.dbEntities.DoctorPatientRelation
import com.example.patientsportal.entities.dbEntities.DoctorPlaces
import com.example.patientsportal.entities.dbEntities.DoctorSpeciality

object ArrayDoctorRelations {

    val arrayDoctorSpecialities = arrayListOf(
        DoctorSpeciality(1, arrayDoctors[0], arraySpecialities[6]),
        DoctorSpeciality(2, arrayDoctors[0], arraySpecialities[22]),
        DoctorSpeciality(3, arrayDoctors[1], arraySpecialities[8]),
        DoctorSpeciality(4, arrayDoctors[1], arraySpecialities[63]),
        DoctorSpeciality(5, arrayDoctors[2], arraySpecialities[71]),
        DoctorSpeciality(6, arrayDoctors[3], arraySpecialities[6]),
        DoctorSpeciality(7, arrayDoctors[4], arraySpecialities[80]),
        DoctorSpeciality(8, arrayDoctors[4], arraySpecialities[74]),
        DoctorSpeciality(9, arrayDoctors[5], arraySpecialities[22]),
        DoctorSpeciality(10, arrayDoctors[6], arraySpecialities[71]),
        DoctorSpeciality(11, arrayDoctors[6], arraySpecialities[73]),
        DoctorSpeciality(12, arrayDoctors[7], arraySpecialities[22]),
        DoctorSpeciality(13, arrayDoctors[8], arraySpecialities[71]),
        DoctorSpeciality(14, arrayDoctors[9], arraySpecialities[18]),
        DoctorSpeciality(15, arrayDoctors[10], arraySpecialities[22]),
        DoctorSpeciality(16, arrayDoctors[11], arraySpecialities[59]),
        DoctorSpeciality(17, arrayDoctors[12], arraySpecialities[84]),
        DoctorSpeciality(18, arrayDoctors[12], arraySpecialities[104]),
        DoctorSpeciality(19, arrayDoctors[13], arraySpecialities[71]),
        DoctorSpeciality(20, arrayDoctors[14], arraySpecialities[36]),
        DoctorSpeciality(21, arrayDoctors[15], arraySpecialities[6]),
        DoctorSpeciality(22, arrayDoctors[16], arraySpecialities[20]),
        DoctorSpeciality(23, arrayDoctors[16], arraySpecialities[81]),
        DoctorSpeciality(24, arrayDoctors[17], arraySpecialities[40]),
        DoctorSpeciality(25, arrayDoctors[18], arraySpecialities[36]),
        DoctorSpeciality(26, arrayDoctors[19], arraySpecialities[92]),
        DoctorSpeciality(27, arrayDoctors[20], arraySpecialities[43]),
        DoctorSpeciality(28, arrayDoctors[21], arraySpecialities[46]),
        DoctorSpeciality(29, arrayDoctors[22], arraySpecialities[36]),
        DoctorSpeciality(30, arrayDoctors[23], arraySpecialities[6]),
        DoctorSpeciality(31, arrayDoctors[24], arraySpecialities[51]),
        DoctorSpeciality(32, arrayDoctors[25], arraySpecialities[34]),
        DoctorSpeciality(33, arrayDoctors[26], arraySpecialities[1]),
        DoctorSpeciality(34, arrayDoctors[27], arraySpecialities[34]),
        DoctorSpeciality(35, arrayDoctors[28], arraySpecialities[3]),
        DoctorSpeciality(36, arrayDoctors[29], arraySpecialities[6]),
        DoctorSpeciality(37, arrayDoctors[30], arraySpecialities[34]),
        DoctorSpeciality(38, arrayDoctors[31], arraySpecialities[34]),
        DoctorSpeciality(39, arrayDoctors[32], arraySpecialities[104]),
        DoctorSpeciality(40, arrayDoctors[33], arraySpecialities[104]),
        DoctorSpeciality(41, arrayDoctors[34], arraySpecialities[104]),
        DoctorSpeciality(42, arrayDoctors[35], arraySpecialities[22]),
        DoctorSpeciality(43, arrayDoctors[36], arraySpecialities[25]),
        DoctorSpeciality(44, arrayDoctors[37], arraySpecialities[3]),
        DoctorSpeciality(45, arrayDoctors[38], arraySpecialities[34]),
        DoctorSpeciality(46, arrayDoctors[39], arraySpecialities[104]),
        DoctorSpeciality(47, arrayDoctors[40], arraySpecialities[36]),
        DoctorSpeciality(48, arrayDoctors[41], arraySpecialities[51]),
        DoctorSpeciality(49, arrayDoctors[42], arraySpecialities[22])
    )

    val arrayDoctorPatients = arrayListOf(
        DoctorPatientRelation(arrayDoctorSpecialities[11], arrayPatients[0]),
        DoctorPatientRelation(arrayDoctorSpecialities[32], arrayPatients[0]),
        DoctorPatientRelation(arrayDoctorSpecialities[22], arrayPatients[0]),
        DoctorPatientRelation(arrayDoctorSpecialities[25], arrayPatients[0]),
        DoctorPatientRelation(arrayDoctorSpecialities[15], arrayPatients[0]),
        DoctorPatientRelation(arrayDoctorSpecialities[35], arrayPatients[0]),
        DoctorPatientRelation(arrayDoctorSpecialities[20], arrayPatients[0]),
        DoctorPatientRelation(arrayDoctorSpecialities[2], arrayPatients[0]),
        DoctorPatientRelation(arrayDoctorSpecialities[14], arrayPatients[0]),
        DoctorPatientRelation(arrayDoctorSpecialities[45], arrayPatients[0]),
        DoctorPatientRelation(arrayDoctorSpecialities[40], arrayPatients[1]),
        DoctorPatientRelation(arrayDoctorSpecialities[29], arrayPatients[1]),
        DoctorPatientRelation(arrayDoctorSpecialities[6], arrayPatients[1]),
        DoctorPatientRelation(arrayDoctorSpecialities[19], arrayPatients[1]),
        DoctorPatientRelation(arrayDoctorSpecialities[7], arrayPatients[1]),
        DoctorPatientRelation(arrayDoctorSpecialities[44], arrayPatients[1]),
        DoctorPatientRelation(arrayDoctorSpecialities[1], arrayPatients[1]),
        DoctorPatientRelation(arrayDoctorSpecialities[23], arrayPatients[1]),
        DoctorPatientRelation(arrayDoctorSpecialities[12], arrayPatients[1]),
        DoctorPatientRelation(arrayDoctorSpecialities[34], arrayPatients[1]),
        DoctorPatientRelation(arrayDoctorSpecialities[16], arrayPatients[2]),
        DoctorPatientRelation(arrayDoctorSpecialities[39], arrayPatients[2]),
        DoctorPatientRelation(arrayDoctorSpecialities[1], arrayPatients[2]),
        DoctorPatientRelation(arrayDoctorSpecialities[25], arrayPatients[2]),
        DoctorPatientRelation(arrayDoctorSpecialities[18], arrayPatients[2]),
        DoctorPatientRelation(arrayDoctorSpecialities[44], arrayPatients[2]),
        DoctorPatientRelation(arrayDoctorSpecialities[20], arrayPatients[2]),
        DoctorPatientRelation(arrayDoctorSpecialities[2], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[4], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[5], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[6], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[7], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[8], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[9], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[10], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[11], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[12], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[13], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[14], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[15], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[16], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[18], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[19], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[20], arrayPatients[3]),
        DoctorPatientRelation(arrayDoctorSpecialities[48], arrayPatients[3])
    )

    val arrayDoctorPlaces = arrayOf(
        DoctorPlaces(1, arrayDoctorSpecialities[0], arrayPlaces[16]),
        DoctorPlaces(2, arrayDoctorSpecialities[1], arrayPlaces[16]),
        DoctorPlaces(3, arrayDoctorSpecialities[2], arrayPlaces[14]),
        DoctorPlaces(4, arrayDoctorSpecialities[3], arrayPlaces[14]),
        DoctorPlaces(5, arrayDoctorSpecialities[4], arrayPlaces[14]),
        DoctorPlaces(6, arrayDoctorSpecialities[4], arrayPlaces[15]),
        DoctorPlaces(7, arrayDoctorSpecialities[5], arrayPlaces[14]),
        DoctorPlaces(8, arrayDoctorSpecialities[6], arrayPlaces[14]),
        DoctorPlaces(9, arrayDoctorSpecialities[7], arrayPlaces[14]),
        DoctorPlaces(10, arrayDoctorSpecialities[8], arrayPlaces[14]),
        DoctorPlaces(11, arrayDoctorSpecialities[9], arrayPlaces[15]),
        DoctorPlaces(12, arrayDoctorSpecialities[10], arrayPlaces[15]),
        DoctorPlaces(13, arrayDoctorSpecialities[9], arrayPlaces[1]),
        DoctorPlaces(14, arrayDoctorSpecialities[10], arrayPlaces[1]),
        DoctorPlaces(15, arrayDoctorSpecialities[11], arrayPlaces[14]),
        DoctorPlaces(16, arrayDoctorSpecialities[11], arrayPlaces[0]),
        DoctorPlaces(17, arrayDoctorSpecialities[12], arrayPlaces[14]),
        DoctorPlaces(18, arrayDoctorSpecialities[12], arrayPlaces[15]),
        DoctorPlaces(19, arrayDoctorSpecialities[13], arrayPlaces[14]),
        DoctorPlaces(20, arrayDoctorSpecialities[14], arrayPlaces[14]),
        DoctorPlaces(21, arrayDoctorSpecialities[15], arrayPlaces[14]),
        DoctorPlaces(22, arrayDoctorSpecialities[16], arrayPlaces[15]),
        DoctorPlaces(23, arrayDoctorSpecialities[17], arrayPlaces[15]),
        DoctorPlaces(24, arrayDoctorSpecialities[18], arrayPlaces[14]),
        DoctorPlaces(25, arrayDoctorSpecialities[19], arrayPlaces[14]),
        DoctorPlaces(26, arrayDoctorSpecialities[19], arrayPlaces[15]),
        DoctorPlaces(27, arrayDoctorSpecialities[20], arrayPlaces[1]),
        DoctorPlaces(28, arrayDoctorSpecialities[20], arrayPlaces[13]),
        DoctorPlaces(29, arrayDoctorSpecialities[21], arrayPlaces[4]),
        DoctorPlaces(30, arrayDoctorSpecialities[22], arrayPlaces[4]),
        DoctorPlaces(31, arrayDoctorSpecialities[21], arrayPlaces[15]),
        DoctorPlaces(32, arrayDoctorSpecialities[22], arrayPlaces[15]),
        DoctorPlaces(33, arrayDoctorSpecialities[23], arrayPlaces[2]),
        DoctorPlaces(34, arrayDoctorSpecialities[23], arrayPlaces[12]),
        DoctorPlaces(35, arrayDoctorSpecialities[23], arrayPlaces[14]),
        DoctorPlaces(36, arrayDoctorSpecialities[24], arrayPlaces[14]),
        DoctorPlaces(37, arrayDoctorSpecialities[25], arrayPlaces[15]),
        DoctorPlaces(38, arrayDoctorSpecialities[26], arrayPlaces[4]),
        DoctorPlaces(39, arrayDoctorSpecialities[27], arrayPlaces[15]),
        DoctorPlaces(40, arrayDoctorSpecialities[28], arrayPlaces[6]),
        DoctorPlaces(41, arrayDoctorSpecialities[29], arrayPlaces[0]),
        DoctorPlaces(42, arrayDoctorSpecialities[29], arrayPlaces[14]),
        DoctorPlaces(43, arrayDoctorSpecialities[30], arrayPlaces[5]),
        DoctorPlaces(44, arrayDoctorSpecialities[31], arrayPlaces[4]),
        DoctorPlaces(45, arrayDoctorSpecialities[32], arrayPlaces[1]),
        DoctorPlaces(46, arrayDoctorSpecialities[33], arrayPlaces[4]),
        DoctorPlaces(47, arrayDoctorSpecialities[34], arrayPlaces[12]),
        DoctorPlaces(48, arrayDoctorSpecialities[35], arrayPlaces[14]),
        DoctorPlaces(49, arrayDoctorSpecialities[36], arrayPlaces[8]),
        DoctorPlaces(50, arrayDoctorSpecialities[37], arrayPlaces[4]),
        DoctorPlaces(51, arrayDoctorSpecialities[38], arrayPlaces[14]),
        DoctorPlaces(52, arrayDoctorSpecialities[39], arrayPlaces[14]),
        DoctorPlaces(53, arrayDoctorSpecialities[39], arrayPlaces[15]),
        DoctorPlaces(54, arrayDoctorSpecialities[40], arrayPlaces[2]),
        DoctorPlaces(55, arrayDoctorSpecialities[40], arrayPlaces[4]),
        DoctorPlaces(56, arrayDoctorSpecialities[41], arrayPlaces[7]),
        DoctorPlaces(57, arrayDoctorSpecialities[42], arrayPlaces[11]),
        DoctorPlaces(58, arrayDoctorSpecialities[43], arrayPlaces[12]),
        DoctorPlaces(59, arrayDoctorSpecialities[44], arrayPlaces[14]),
        DoctorPlaces(60, arrayDoctorSpecialities[45], arrayPlaces[14]),
        DoctorPlaces(61, arrayDoctorSpecialities[46], arrayPlaces[15]),
        DoctorPlaces(62, arrayDoctorSpecialities[47], arrayPlaces[9]),
        DoctorPlaces(63, arrayDoctorSpecialities[48], arrayPlaces[14])
    )
}