package com.example.patientsportal.db.arrays

import com.example.patientsportal.entities.dbEntities.Speciality

object ArraySpecialities {

    val arraySpecialities = arrayListOf(
        Speciality(0, "Adolescencia"),
        Speciality(1, "Alergia"),
        Speciality(2, "Andrologia - Reproduccion - Servicio de Urologia"),
        Speciality(3, "Anestesiologia"),
        Speciality(4, "Arritmias Y Deportologia - Cardiologia Pediatria"),
        Speciality(5, "Artroscopia y Protesis de rodilla"),
        Speciality(6, "Cardiologia"),
        Speciality(7, "Cardiologia Pediatrica"),
        Speciality(8, "Cefaleas"),
        Speciality(9, "Cirugia de Cabeza y Cuello"),
        Speciality(10, "Cirugia de Esofago, Estomago y Duodeno"),
        Speciality(11, "Cirugia de Higado, Via Biliar y Pancreas"),
        Speciality(12, "Cirugia de Paredes Abdominales"),
        Speciality(13, "Cirugia de Torax"),
        Speciality(14, "Cirugia General"),
        Speciality(15, "Cirugia General Pediatrica"),
        Speciality(16, "Cirugia Laparoscopica y Endoscopica"),
        Speciality(17, "Cirugia Pediatrica"),
        Speciality(18, "Cirugia Plástica"),
        Speciality(19, "Cirugia Plástica Pediatrica"),
        Speciality(20, "Climaterio"),
        Speciality(21, "Clinica de Mielomeningocele"),
        Speciality(22, "Clinica Medica"),
        Speciality(23, "Coloproctologia"),
        Speciality(24, "Cornea y Cirugia Refractiva"),
        Speciality(25, "Demanda Espontanea Ortopedia"),
        Speciality(26, "Dermatologia"),
        Speciality(27, "Diabetes - Endocrinologia"),
        Speciality(28, "Endocrinologia Ambulatoria"),
        Speciality(29, "Endocrinologia Ginecologica"),
        Speciality(30, "Endocrinologia Masculina"),
        Speciality(31, "Endocrinologia Pediatrica y Crecimiento"),
        Speciality(32, "Enfermedades Cerebrovasculares"),
        Speciality(33, "Estrabismo"),
        Speciality(34, "Evaluacion Clinica Prequirurgica"),
        Speciality(35, "Flebolinfologia"),
        Speciality(36, "Gastroenterologia"),
        Speciality(37, "Gastroenterologia Pediatrica"),
        Speciality(38, "Ginecologia - Oncologia"),
        Speciality(39, "Ginecologia Endocrinologica"),
        Speciality(40, "Ginecologia General"),
        Speciality(41, "Glaucoma"),
        Speciality(42, "Hemato-oncologia Pediatrica"),
        Speciality(43, "Hematologia"),
        Speciality(44, "Hepatologia"),
        Speciality(45, "Hepatologia Pediatrica"),
        Speciality(46, "Hipertension"),
        Speciality(47, "Hipofisis - Neuroendocrinologia"),
        Speciality(48, "Infectologia"),
        Speciality(49, "Infectologia Pediatrica"),
        Speciality(50, "Infectologia y Superficie Ocular"),
        Speciality(51, "Kinesiologia"),
        Speciality(52, "Laringe"),
        Speciality(53, "Med Ambulatoria y Atencion Primaria Pediatrica"),
        Speciality(54, "Medicina Familiar"),
        Speciality(55, "Medicina Paliativa"),
        Speciality(56, "Nefrologia"),
        Speciality(57, "Nefrologia Pediatrica"),
        Speciality(58, "Neonatologia"),
        Speciality(59, "Neumonologia"),
        Speciality(60, "Neumonologia Pediatrica"),
        Speciality(61, "Neurocirugia"),
        Speciality(62, "Neurocirugia Pediatrica"),
        Speciality(63, "Neurologia"),
        Speciality(64, "Neurologia - Epilepsia"),
        Speciality(65, "Neurologia - Movimientos Anormales y Parkinson"),
        Speciality(66, "Neurologia Pediatrica"),
        Speciality(67, "Nutricion"),
        Speciality(68, "Nutricion Pediatrica"),
        Speciality(69, "Obstetricia"),
        Speciality(70, "Oculoplastica, Vias Lagrimales y Orbita"),
        Speciality(71, "Oftalmologia"),
        Speciality(72, "Oncologia"),
        Speciality(73, "Oncologia Ocular"),
        Speciality(74, "Orl - Alergia"),
        Speciality(75, "Orl - Cabeza y Cuello"),
        Speciality(76, "Ortopedia Oncologica y Transplantes Oseos"),
        Speciality(77, "Osteopatias Metabolicas - Endocrinologia"),
        Speciality(78, "Otologia"),
        Speciality(79, "Otoneurologia"),
        Speciality(80, "Otorrinolaringologia"),
        Speciality(81, "Patologia Cervical Ginecologica"),
        Speciality(82, "Patologia de Cadera"),
        Speciality(83, "Patologia de Hombro"),
        Speciality(84, "Patologia de Pie y Tobillo"),
        Speciality(85, "Patologia del Miembro Superior"),
        Speciality(86, "Patologia del Raquis"),
        Speciality(87, "Patologia Pelviana Benigna"),
        Speciality(88, "Patologia Raquimedular"),
        Speciality(89, "Patologia Vulvar e Infecciones Vulvovaginales"),
        Speciality(90, "Planificacion Familiar"),
        Speciality(91, "Radiologia Intervencionista"),
        Speciality(92, "Reproduccion - Ginecologia"),
        Speciality(93, "Retina"),
        Speciality(94, "Reumatologia"),
        Speciality(95, "Reumatologia Pediatrica"),
        Speciality(96, "Rinologia Plastica"),
        Speciality(97, "Rinosinusologia"),
        Speciality(98, "Roncopatias"),
        Speciality(99, "Seccion Cirugia Bariatrica"),
        Speciality(100, "Toxicologia"),
        Speciality(101, "Trastornos de Memoria y Conducta"),
        Speciality(102, "Trastornos del Sueño - Servicio de Neurologia"),
        Speciality(103, "Tratamiento del Dolor - Anestesia"),
        Speciality(104, "Traumatologia y Ortopedia"),
        Speciality(105, "Unidad de Cuidados Preventivos"),
        Speciality(106, "Uroginecologia"),
        Speciality(107, "Urologia"),
        Speciality(108, "Urologia Pediatrica"),
        Speciality(109, "Uveitis")
    )


}