package com.example.patientsportal.objects

import com.example.patientsportal.entities.PregnancyWeek

object PregnancyWeeks {

    fun getPregnancyWeeks(): ArrayList<PregnancyWeek> {
        return arrayListOf(
            PregnancyWeek(1, "", """
    <b>Estudios en esta semana:</b>
    <ul>
        <li><b>Ecografía precoz</b></li>
        <li><b>Laboratorios de rutina:</b> Incluyen análisis de sangre para detección de anemia, serologías (para estudiar enfermedades como el VIH o Sífilis) y análisis de orina para detectar infecciones urinarias asintomáticas</li>
        <li><b>Grupo y factor:</b> Es muy importante para prevenir la enfermedad por inmunización Rh y sus complicaciones en futuros embarazos</li>
        <li><b>Historia clínica detallada:</b> Sirve para evaluar su salud y su estilo de vida, cuáles son sus actividades cotidianas, dieta, consumo de medicamentos, alergias, conocer su historia obstétrica y familiar en busca de factores de riesgo</li>
        <li><b>Suplementación con ácido fólico:</b> Si usted ya estaba consumiendo, deberá continuar por algunas semanas más. Si no lo estaba haciendo, este es un buen momento para comenzar. Esta medicación previene defectos de cierre del tubo neural en el bebé</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/estudiosimagenes.jpg", "", "En este momento usted no sabrá si está embarazada.  De todos modos, algunas mujeres pueden sentir cambios hormonales desde muy temprano, pero el síntoma más importante para sospechar un embarazo será la ausencia de la menstruación, para lo que falta cerca de una semana. Los cambios emocionales son muy frecuentes durante todo el embarazo. Usted puede sentirse algo inestable o tener cambios frecuentes de humor.\n" +
                    "\n" +
                    "Cuando el blastocisto se implanta en la cavidad uterina, un grupo de mujeres puede tener una pequeña pérdida de sangre amarronada durante 2 o 3 días.  Esta pérdida no suele tener importancia en la salud del embarazo y no debe alarmar.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/pechos-04.png", "", "La fecundación del óvulo por el espermatozoide finaliza cuando los cromosomas (estructuras que llevan el ADN) del padre y de la madre se han mezclado. El huevo (primera célula del bebé) comienza a dividirse al día siguiente de la fecundación, y para alrededor del 4to día llega a tener  un número total de 12 células (ahora se llama mórula).\n" +
                    "\n" +
                    "Cuando ya existe un número considerable de células, las mismas se dividen en dos grupos, uno interno que dará origen al embrión y el otro grupo que rodea al anterior que dará origen a la placenta (en este momento se llama blastocisto). Mientras las células del blastocisto se dividen, este se va desplazando a través los conductos que lo llevan al útero (trompas de Falopio). Allí el blastocisto se implanta (se introduce en la pared)  del útero entre los días 6-7° post fecundación.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/1%20mes-01.png"),
            PregnancyWeek(2, "", """
    <b>Estudios en esta semana:</b>
    <ul>
        <li><b>Ecografía precoz</b></li>
        <li><b>Laboratorios de rutina:</b> Incluyen análisis de sangre para detección de anemia, serologías (para estudiar enfermedades como el VIH o Sífilis) y análisis de orina para detectar infecciones urinarias asintomáticas</li>
        <li><b>Grupo y factor:</b> Es muy importante para prevenir la enfermedad por inmunización Rh y sus complicaciones en futuros embarazos</li>
        <li><b>Historia clínica detallada:</b> Sirve para evaluar su salud y su estilo de vida, cuáles son sus actividades cotidianas, dieta, consumo de medicamentos, alergias, conocer su historia obstétrica y familiar en busca de factores de riesgo</li>
        <li><b>Suplementación con ácido fólico:</b> Si usted ya estaba consumiendo, deberá continuar por algunas semanas más. Si no lo estaba haciendo, este es un buen momento para comenzar. Esta medicación previene defectos de cierre del tubo neural en el bebé</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/estudiosimagenes.jpg", "", "Los cambios hormonales que sufre el cuerpo de la mujer en esta semana están dados principalmente por el aumento de los estrógenos y la progesterona. Su cuerpo sabrá de esta manera que está embarazada y acompañará a estos cambios necesarios para el desarrollo adecuado del bebé.\n" +
                    "\n" +
                    "Los síntomas más comunes que usted puede sentir en esta etapa son puntadas en la parte baja del abdomen y tensión mamaria. Éstos síntomas no difieren demasiado de los de la ovulación o el periodo premenstrual, por lo tanto muchas mujeres aún no saben de su embarazo a esta altura.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M02%20-ovarios.png", "", "Se desarrolla el embrión, que tiene la forma de un disco y pueden comenzar a distinguirse la zona donde estará la cabeza y el resto del cuerpo. Las primeras semanas del desarrollo embrionario son muy importantes porque comienza el proceso de organogénesis, es decir, la formación de los órganos del bebé (sistema nervioso, sistema cardiovascular, sistema digestivo, pulmones, riñones, músculo, huesos, piel).\n" +
                    "\n" +
                    "También durante esta semana comienza el desarrollo de la circulación de sangre entre la mamá y la placenta, lo que permitirá que su bebé se alimente y oxigene durante todo el embarazo.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/1%20mes-02.png"),
            PregnancyWeek(3, "", """
    <b>Estudios en esta semana:</b>
    <ul>
        <li><b>Ecografía precoz</b></li>
        <li><b>Laboratorios de rutina:</b> Incluyen análisis de sangre para detección de anemia, serologías (para estudiar enfermedades como el VIH o Sífilis) y análisis de orina para detectar infecciones urinarias asintomáticas</li>
        <li><b>Grupo y factor:</b> Es muy importante para prevenir la enfermedad por inmunización Rh y sus complicaciones en futuros embarazos</li>
        <li><b>Historia clínica detallada:</b> Sirve para evaluar su salud y su estilo de vida, cuáles son sus actividades cotidianas, dieta, consumo de medicamentos, alergias, conocer su historia obstétrica y familiar en busca de factores de riesgo</li>
        <li><b>Suplementación con ácido fólico:</b> Si usted ya estaba consumiendo, deberá continuar por algunas semanas más. Si no lo estaba haciendo, este es un buen momento para comenzar. Esta medicación previene defectos de cierre del tubo neural en el bebé</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/estudiosimagenes.jpg", "", "Usted aún no sabrá que está embarazada pero las pruebas de embarazo ya pueden dar resultados positivos. Es bastante frecuente presentar alguno de los siguientes síntomas: dolor de pechos, cansancio y náuseas, aumento de las ganas de orinar, dolor de cabeza, etc.\n" +
                    "\n" +
                    "Si usted está buscando embarazo pero aún no sabe que ya está embarazada, intente igualmente mejorar la calidad de los alimentos que consume, aumente la ingesta de hierro, ácido fólico, calcio, frutas y vegetales, hidrátese y descanse todo lo que pueda.\n" +
                    "Usted ahora, deberá cuidar de su salud y la de su bebé.  Un estilo de vida saludable, es ideal en toda esta etapa.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/cansancio-01.png", "", "Está en una etapa crucial de la formación de sus órganos. El corazón de su bebé ya comienza a latir, a una frecuencia media de 150 latidos por minuto, y esto puede ser observado mediante una ecografía.\n" +
                    "\n" +
                    "Comienzan a desarrollarse el esqueleto, el sistema nervioso central y el aparato cardiovascular, que está formado por un corazón tubular que se encuentra unido a vasos sanguíneos del bebé, del cordón umbilical y de la futura placenta. Se van formando y expandiendo las vellosidades de la placenta, que al estar bañadas  por sangre materna, permiten  el intercambio de oxígeno y nutrientes entre el bebé y la mamá.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/1%20mes-03.png"),
            PregnancyWeek(4, "", """
    <b>Estudios en esta semana:</b>
    <ul>
        <li><b>Ecografía precoz</b></li>
        <li><b>Laboratorios de rutina:</b> Incluyen análisis de sangre para detección de anemia, serologías (para estudiar enfermedades como el VIH o Sífilis) y análisis de orina para detectar infecciones urinarias asintomáticas</li>
        <li><b>Grupo y factor:</b> Es muy importante para prevenir la enfermedad por inmunización Rh y sus complicaciones en futuros embarazos</li>
        <li><b>Historia clínica detallada:</b> Sirve para evaluar su salud y su estilo de vida, cuáles son sus actividades cotidianas, dieta, consumo de medicamentos, alergias, conocer su historia obstétrica y familiar en busca de factores de riesgo</li>
        <li><b>Suplementación con ácido fólico:</b> Si usted ya estaba consumiendo, deberá continuar por algunas semanas más. Si no lo estaba haciendo, este es un buen momento para comenzar. Esta medicación previene defectos de cierre del tubo neural en el bebé</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/estudiosimagenes.jpg", "", "Es muy probable que todavía usted no sepa que está embarazada, aunque ya puede que tenga un atraso menstrual.  De ser así, es conveniente realizar un test de embarazo en orina o en sangre para corroborarlo. Preste atención a su cuerpo, es probable que se sienta con más sueño de lo normal, muchas ganas de orinar y más cansancio que de costumbre.\n" +
                    "\n" +
                    "Las primeras semanas de embarazo no suelen ser las mejores, pues al cansancio se le pueden añadir vómitos matutinos y una intensificación en la percepción de los olores. La buena noticia es que, ¡todos estos síntomas en la mayoría de las mujeres mejoran con el correr del tiempo!", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/retraso-06.png", "", "El evento más significativo de esta semana es el rápido crecimiento del embrión y como consecuencia, su cambio de forma. Pasa de ser un disco plano a tener la forma de un cilindro, pudiéndose diferenciar un extremo donde estará la cabeza del bebé (extremo cefálico).  Esto se debe a que el embrión comienza a plegarse gracias a su rápido crecimiento. El embrión tiene el tamaño aproximado de 2-3 mm y crece 1 milímetro al día.\n" +
                    "\n" +
                    "Al producirse el plegamiento del embrión, la capa más interna de tejidos (endodermo) dará origen al aparato respiratorio y digestivo principalmente.  La capa media (mesodermo) formará los músculos, huesos, órganos genitales internos (ovarios y testículos), el corazón y los vasos sanguíneos y linfáticos.  La capa más externa (ectodermo) será la responsable de la formación del sistema nervioso y la piel.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/1%20mes-04.png"),
            PregnancyWeek(5, "", "", "", "", "La mayoría de las mujeres pueden presentar alguno de los siguientes síntomas: cansancio, náuseas y vómitos (sobre todo al levantarte por la mañana), aumento del volumen de los senos, mayores ganas de orinar (dado que el crecimiento del útero ejerce presión sobre la vejiga), presión en la pelvis y la cadera. Algunas mujeres no perciben señales de embarazo y sólo lo descubren por el retraso de la menstruación.\n" +
                    "\n" +
                    "Por la acción de las hormonas usted puede notar cierto grado de inestabilidad emocional. No se preocupe, esto es totalmente normal. Igualmente, siempre que usted sienta o perciba que algo no anda bien, no dude consultarlo con su médico.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/pregnancy%20test-05.png", "", "En estas primeras semanas de embarazo, el crecimiento del embrión es muy grande.  Desde la concepción hasta este momento el embrión ha aumentado prácticamente 40 veces su tamaño.\n" +
                    "\n" +
                    "Durante esta semana sí puede observarse un notorio crecimiento de la cabeza.  Esto se debe principalmente al rápido aumento del tamaño del cerebro. Ya pueden verse también los esbozos de los brazos (que tienen forma de paleta) y de las piernas (con forma de aletas).", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/1%20mes-05.png"),
            PregnancyWeek(6, "", "", "", "", "El cansancio, los vómitos y el resto de los síntomas mencionados pueden hacerse mucho más intensos a partir de esta semana.\n" +
                    "\n" +
                    "Recuerde descansar todo lo que pueda, hidratarse y comer cada 3 horas, esto le ayudará a mejorar el malestar que producen las náuseas y los vómitos.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/Documentos/emabarazada%20sleep-01.png", "", "El embrión ya mide entre 5 y 7 mm y continúa creciendo aproximadamente 1 mm por día. El tamaño de la cabeza en relación al del cuerpo es mucho mayor y ya aparecen los ojos. Los miembros superiores (brazos y manos) se desarrollan más rápido que los miembros inferiores (piernas y pies). \n" +
                    "\n" +
                    "Pueden distinguirse el codo y las manos primitivas, además de que el embrión comienza a realizar movimientos espontáneos del tronco y las extremidades.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/1%20mes-06.png"),
            PregnancyWeek(7, "", "", "", "", "Usted ya sabe que está embarazada y alrededor de esta semana es un buen momento para consultar a un ginecólogo u obstetra. Puede ser que usted haya aumentado de peso pero es probable que todavía no se note la “panza”.\n" +
                    "\n" +
                    "Las primeras semanas del bebé son claves, por lo tanto le sugerimos evitar cualquier situación que pueda poner en riesgo el adecuado desarrollo del embrión: no es bueno que usted ingiera medicación sin previa consulta a su médico. Tampoco es recomendable el consumo de alcohol o drogas, además de que debe intentar evitar el tabaco.  ", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/medicamentos%20prohibidos-01.png", "", "Los brazos y las piernas sufren muchas modificaciones durante esta semana, aparecen surcos entre los dedos y tanto los brazos como las piernas se aproximan entre sí en la línea media, además de que los huesos adquieren forma y el cerebro continúa desarrollándose. El embrión mide aproximadamente 10 mm. \n" +
                    "\n" +
                    "La placenta sigue formándose, y el cordón umbilical empieza a crecer y ensancharse. La neurogénesis es un proceso de división celular rápida que produce millones de neuronas. ", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/1manos%20y%20pies.png"),
            PregnancyWeek(8, "", "", "", "", "En esta semana es probable que usted continúe sintiendo las mismas molestias que previamente mencionamos (náuseas y vómitos matutinos, más ganas de orinar, presión en la pelvis). En muchas mujeres durante esta semana los síntomas pueden intensificarse.\n" +
                    "\n" +
                    "El útero ha aumentado notablemente de tamaño, por lo tanto, usted puede sentir mayor presión en la pelvis y en la parte inferior del abdomen. Su médico seguramente ya le ha solicitado los estudios de rutina y una ecografía para valorar la vitalidad, la localización y el tamaño de su bebé.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M08%20-%20matutinas.png", "", "Finaliza el periodo embrionario. Su bebé deja de ser un embrión para transformarse en un feto que ya tiene párpados, labio superior y las orejas se están empezando a formar. La placenta asume la función de nutrir a su bebé a través del cordón umbilical. A esta altura del embarazo el feto mide aproximadamente entre 15 y 20 milímetros.\n" +
                    "\n" +
                    "El cuerpo se alarga y la cola desaparece. Pueden reconocerse surcos que dividen los dedos de manos y pies. Es posible ver el esqueleto a través de su piel y las extremidades (brazos y piernas) pueden realizar movimientos intencionados.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/08%20-%20cara.png"),
            PregnancyWeek(9, "", "", "", "", "A las molestias del primer trimestre que ya venimos mencionando pueden sumarse acidez, sensación de panza hinchada (por aumento de gases) y constipación. No desespere, todos estos síntomas suelen mejorar en el segundo trimestre.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M09%20-%20acidez.png", "", "La cabeza del feto ocupa aproximadamente el 50% del tamaño total de cabeza a cola. Un feto de 9 semanas mide aproximadamente entre 30-40 mm. La cara de su bebé es muy ancha y sus ojos se encuentran bastante separados. Los párpados se han terminado de formar pero continúan fusionados. Los huesos pueden visualizarse cada vez mejor a medida que avanzan las semanas.\n" +
                    "\n" +
                    "El sistema nervioso extiende sus conexiones por todo el cuerpo, por eso el bebé realizará movimientos espasmódicos e involuntarios. El bebé ya se mueve, aunque usted todavía no lo sienta. Los genitales de los bebés masculinos y femeninos ya están diferenciados a esta altura, pero aún la forma es similar en ambos sexos.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/09%20-%20semana%209.png"),
            PregnancyWeek(10, "", "", "", "", "Usted irá de a poco notando que aumenta de peso, sobre todo porque su ropa queda más ajustada. No dude en cambiar el talle de su corpiño, las mamas aumentan bastante de tamaño en el primer trimestre y pueden incluso doler. Un buen sostén le brindará a usted confort.\n" +
                    "\n" +
                    "Probablemente usted ya tenga asignada una cita con el médico. Le solicitará una serie de exámenes para determinar que todo esté bien además de realizar el control de su peso y presión arterial. También hará preguntas de rutina sobre sus antecedentes obstétricos (si ya tiene hijos, de que forma nacieron, si tuvo algún aborto, etc.) y sus antecedentes personales y familiares (enfermedades que usted haya tenido o que algún miembro de su familia tenga). Todo esto es de mucha importancia para la salud de su embarazo. Puede preparar una lista con preguntas e inquietudes para llevar a la consulta.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M10%20-%20pantalon.png", "", "Los intestinos crecen y comienzan a colocarse en su lugar, para cerca de la semana 12 observarse todo el intestino dentro del abdomen. Además, el cerebro crece muy rápidamente, multiplicando el número de neuronas a gran velocidad.\n" +
                    "\n" +
                    "Alrededor de esta semana comienza la diferenciación externa de los órganos sexuales, aunque todavía es difícil saber el sexo del bebé.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/10%20-%20cerebro.png"),
            PregnancyWeek(11, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Ecografía 11-14 (screening, DPN test, TN plus):</b> Esta ecografía le brinda al médico y a usted mucha información sobre la salud de su bebé.  En forma opcional, puede también extraerse sangre materna.  Con éste estudio se puede estimar el riesgo de que su bebé tenga:</li>
        <li><b>Anomalías de cromosomas (ejemplo Trisomía 21, también denominado Sindrome de Down)</b></li>
        <li><b>Malformaciones severas</b></li>
        <li><b>Problemas en el crecimiento durante el embarazo:</b> Así como también se puede valorar el riesgo de que usted desarrolle algún problema hipertensivo en el transcurso del embarazo. Si usted desea conocer más sobre los métodos diagnósticos para anomalías de cromosomas, deberá hablarlo con su obstetra durante la consulta.</li>
        <li><b>Suplementación con hierro o complejos multivitamínicos:</b> En base a los resultados de su laboratorio,  su médico evaluará la necesidad o no de que usted tome algún suplemento.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/ecograf.jpg", "", "Las molestias matutinas comienzan a desaparecer en la mayoría de las mujeres embarazadas. Sin embargo, en algunas mujeres pueden extenderse.\n" +
                    "\n" +
                    "Es posible que usted sienta que su respiración es más rápida o tenga episodios de palpitaciones. Esto es bastante frecuente debido a que la cantidad de sangre en su cuerpo aumenta con el correr de las semanas. También es muy común que algunas mujeres produzcan mayor cantidad de saliva o tengan sangrado en encías y nariz. En el caso del sangrado de encías, se sugiere consultar al odontólogo debido a que la salud bucal es muy importante en esta etapa.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M11%20-%20cansada%20agitada.png", "", "En esta semana el feto mide cerca de 50-60 mm. El cuerpo del bebé continúa alargándose y cada vez realiza movimientos más complejos.\n" +
                    "\n" +
                    "En las primeras semanas de embarazo el líquido que rodea al bebé era producido fundamentalmente por las membranas que lo rodeaban. Ahora, los riñones del bebé son la fuente más importante de líquido amniótico.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/11%20-%20ri%C3%B1ones.png"),
            PregnancyWeek(12, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Ecografía 11-14 (screening, DPN test, TN plus):</b> Esta ecografía le brinda al médico y a usted mucha información sobre la salud de su bebé.  En forma opcional, puede también extraerse sangre materna.  Con éste estudio se puede estimar el riesgo de que su bebé tenga:</li>
        <li><b>Anomalías de cromosomas (ejemplo Trisomía 21, también denominado Sindrome de Down)</b></li>
        <li><b>Malformaciones severas</b></li>
        <li><b>Problemas en el crecimiento durante el embarazo:</b> Así como también se puede valorar el riesgo de que usted desarrolle algún problema hipertensivo en el transcurso del embarazo. Si usted desea conocer más sobre los métodos diagnósticos para anomalías de cromosomas, deberá hablarlo con su obstetra durante la consulta.</li>
        <li><b>Suplementación con hierro o complejos multivitamínicos:</b> En base a los resultados de su laboratorio,  su médico evaluará la necesidad o no de que usted tome algún suplemento.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/ecograf(1).jpg", "", "Algunas mujeres pueden presentar acidez en el estómago.  Este es un síntoma que puede presentarse desde ahora y hasta el final del embarazo.  Puede ser útil para aliviarlo evitar comidas que irriten el estómago (café, frituras, picantes) y comer cada dos horas alguna pequeña colación.\n" +
                    "\n" +
                    "Los síntomas que caracterizaron el primer trimestre de embarazo como las náuseas y los vómitos comienzan a desaparecer. Algunas mujeres pueden comenzar a ver el aumento de volumen en su abdomen.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/belly-02.png", "", "En esta semana se forman las cuerdas vocales y se desarrollan las uñas en pies y manos. La cabeza es más redondeada y su perfil se va definiendo. Si bien su cuerpo fue creciendo a gran velocidad y en esta semana mide aproximadamente 70 mm, la cabeza continúa siendo significativamente de mayor tamaño. Esto puede verse en la ecografía indicada esta semana.\n" +
                    "\n" +
                    "El feto es capaz de tragar el líquido amniótico para luego eliminarlo mediante la orina. Los intestinos se ubicarán completamente en el abdomen, ya que en este momento tienen suficiente lugar para hacerlo.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/12%20-%20feto.png"),
            PregnancyWeek(13, "", "", "", "", "A partir del segundo trimestre, su cuerpo empezará a cambiar. La cintura se ensancha y es probable que haya aumentado un poco de peso. Es frecuente que los olores le produzcan malestar, debido a que el sentido del olfato está mucho más agudo. Intente evitar los olores que le produzcan malestar.\n" +
                    "\n" +
                    "Es muy común que aumente la cantidad de flujo vaginal. Si esta situación no le produce síntomas (secreción con mal olor, de color verdoso, picazón, ardor), usted no debería preocuparse.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M13%20-%20olor.png", "", "En esta semana el feto mide entre 70 y 80 mm aproximadamente. La cara va adquiriendo los rasgos habituales debido a que los ojos, que estaban muy separados en las primeras semanas, se han ido desplazando hacia el centro de la cara. Las orejas también se acercan a su posición definitiva, un poco por debajo de los ojos y a los lados.\n" +
                    "\n" +
                    "Ya puede producir sus propios glóbulos rojos (células encargadas de llevar oxígeno a todos los tejidos del cuerpo), pero a diferencia de los niños o adultos que los producen en la médula ósea, en el feto el encargado de este proceso es el hígado.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/13%20cara.png"),
            PregnancyWeek(14, "", "", "", "", "Usted ha comenzado el segundo trimestre, uno de los mejores momentos del embarazo debido a que la mayoría de las molestias que puede haber tenido previamente seguramente estén desapareciendo en forma progresiva.\n" +
                    "\n" +
                    "¡A disfrutar entonces de esta etapa!", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M14%20-%20mujer%20bien.png", "", "En esta semana el feto mide entre 80 y 95 mm. El cuerpo empieza a crecer más rápido y muy lentamente la diferencia entre cabeza y cuerpo es menor.  El cuello se alarga y aparece el vello que recubre la piel (lanugo).\n" +
                    "\n" +
                    "Los músculos de la cara están más desarrollados. El feto puede abrir la boca pareciendo que realiza un bostezo e incluso por momentos puede llevar el dedo a la boca. También a esta altura podemos observar que deglute líquido amniótico mucho más seguido, el cual cumple un papel fundamental en el desarrollo de muchos órganos, sobre todo pulmones y tubo disgestivo.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/14%20dedo.png"),
            PregnancyWeek(15, "", "", "", "", "A partir de esta etapa es muy común observar repentinos cambios de ánimo. En el mismo día puede pasar de sentirse sumamente alegre a un estado de ansiedad, angustia o tristeza. No se asuste, esto se debe generalmente a los cambios hormonales del embarazo. También es frecuente sentirse más torpe o despistada.\n" +
                    "\n" +
                    "Es ideal comenzar a hacer algún tipo de actividad física. Además de permitirle mantener un peso adecuado, hará que usted se encuentre de mejor ánimo. Hable con su médico sobre qué tipo de actividad es conveniente que usted realice según sus gustos y posibilidades.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M15%20-%20cambios%20humor%2B.png", "", "La madres primerizas comienzan a percibir los movimientos como tales a partir de las 20 semanas, aunque algunas manifiestan la sensación de puntadas pequeñas en la parte inferior del abdomen.\n" +
                    "\n" +
                    "Algunas mujeres que ya han tenido otros hijos, puede que a partir de esta semana refieran sentir algunos movimientos del bebé.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M16%20-%20latidos.png"),
            PregnancyWeek(16, "", "", "", "", "La madres primerizas comienzan a percibir los movimientos como tales a partir de las 20 semanas, aunque algunas manifiestan la sensación de puntadas pequeñas en la parte inferior del abdomen.\n" +
                    "\n" +
                    "Algunas mujeres que ya han tenido otros hijos, puede que a partir de esta semana refieran sentir algunos movimientos del bebé.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M16%20-%20latidos.png", "", "Finalmente, el cuerpo del bebé es de mayor tamaño que la cabeza, los ojos y las orejas se encuentran en su posición definitiva. Brazos y piernas tienen proporciones finales. En esta semana ya pesa unos unos 80 gramos y los latidos del corazón de su bebé pueden escucharse fácilmente con un dispositivo especial. Su médico probablemente pueda escucharlos en la consulta.\n" +
                    "\n" +
                    "El reflejo de prensión ya está presente debido a que su bebé es capaz de flexionar, abrir y cerrar los dedos de la mano. No es raro ver que pueden tomarse las manos y los pies. La cantidad de líquido amniótico a partir de ahora depende totalmente de la función de los riñones.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/16%20manos.png"),
            PregnancyWeek(17, "", "", "", "", "Aparecen situaciones nuevas que pueden resultar incómodas. Algunas mujeres pueden presentar constipación y esto acarrear la complicación de las hemorroides. Para prevenir esta situación es ideal que usted consuma buena cantidad de líquido y una dieta rica en fibras. No es raro que muchas mujeres presenten secreción por los pezones y un aumento importante en tamaño de sus mamas.\n" +
                    "\n" +
                    "El bebé comienza a tener periodos de sueño y vigilia.  Si usted ya percibe sus movimientos, notará que por momentos son más fuertes.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M17%20-%20agua.png", "", "Se parece cada vez más a un bebé recién nacido, aunque los ojos aún son bastante grandes en proporción al resto de la cara. El oído ya está bastante desarrollado y es común que el feto se mueva frente a sonidos fuertes provenientes del exterior. Pesa unos 100-110 gramos.\n" +
                    "\n" +
                    "Una particularidad de esta etapa es que aparece el unto sebáceo, una sustancia blanquecina y oleosa que recubre el cuerpo del bebé para proteger la piel hasta le final del embarazo. También se inicia la aparición del tejido adiposo, muy importante en el recién nacido para mantener el calor corporal.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/17%20oido.png"),
            PregnancyWeek(18, "", "", "", "", "El abdomen ya habrá crecido lo suficiente y es probable que ya se note que usted está embarazada. Es común sentirse con menos cansancio y  más energía. Aproveche esta etapa para realizar actividad física.\n" +
                    "\n" +
                    "Los movimientos del bebé más fuertes, por lo tanto las mujeres que cursan su primer embarazo ya pueden comenzar a sentir algunos movimientos.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/more%20belly-04.png", "", "Como su oído ya se desarrolló por completo, se cree que el bebé podría escuchar sonidos. El corazón, que antes era una cavidad rudimentaria, ya puede observarse claramente dividido en cuatro cavidades (dos aurículas y dos ventrículos) por ecografía. El bebé ya tiene un tamaño considerable (cerca de 15 cm) y pesa alrededor de 150 gramos.\n" +
                    "\n" +
                    "A esta altura se pueden observar centros de osificación en los huesos (depósitos de calcio). Estos crecen hacia los extremos de los huesos.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/18%20patada.png"),
            PregnancyWeek(19, "", "", "", "", "Es probable que observe que sus piernas se hinchan. Esto se debe a retención de líquido fuera de los vasos sanguíneos. A veces pueden aparecer varices, tanto en las piernas como en la vulva.  De ser así, hable con su médico al respecto. Una sugerencia para prevenir la retención de líquidos es consumir buena cantidad de agua, hacer actividad física, no permanecer mucho tiempo sentada y dormir de costado, sobre todo izquierdo.\n" +
                    "\n" +
                    "Es común sentir que su bebé tiene hipo.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M19%20dormir.png", "", "El sistema nervioso central se está desarrollando rápidamente, en especial áreas destinadas a los sentidos del gusto, el olfato, la audición, la visión y el tacto. Los periodos de sueño y vigilia son mucho más notorios.  Su peso es de 200 gramos, aproximadamente.\n" +
                    "\n" +
                    "Si bien el sexo del bebé está definido hace tiempo, los genitales del bebé se observan fácilmente por ecografía y es común que usted se entere del sexo del bebé con más certeza en esta etapa.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/sexo-02.png"),
            PregnancyWeek(20, "", """<b>Esta semana debe realizar:</b>
            <ul>
            <li><b>Examen físico obstétrico:</b> Escuchar los latidos en el consultorio le permite a su médico valorar la salud del bebé. A partir de ahora, su médico escuchará los latidos del bebé en cada visita.</li>
            </ul>""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/controlemb(1).jpg", "", "Entre las semanas 19 a 22 los movimientos del bebé comienzan a percibirse como patadas dentro de su abdomen. Si previamente usted no logró sentir ningún movimiento del bebé, lo notará ahora.\n" +
                    "\n" +
                    "El útero llegará un poco por encima del ombligo y usted ya se verá como una mujer embarazada.  El crecimiento del abdomen puede provocarle la sensación de falta de aire. Es muy frecuente sentirse cansada y con mucho sueño.  Lo ideal es descansar todo lo que usted pueda, hacer siestas y dormir 8 hs por las noches.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M20%20-%20movimientos.png", "", "Mide cerca de 16-18 cm y pesa aproximadamente 250 gramos. Sus principales órganos ya están formados, por lo tanto en la ecografía que se realiza en esta semana (scan fetal) puede valorarse su correcto desarrollo. Tiene la forma y las proporciones similares a las que tendrá al nacimiento.\n" +
                    "\n" +
                    "Comienzan a aparecer las huellas digitales de palmas y plantas de los pies. Continúa acumulando grasa y está totalmente cubierto por unto sebáceo, que protegerá su piel del líquido amniótico.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/20%20ecografia.png"),
            PregnancyWeek(21, "", "", "", "", "Seguramente usted se sienta muy bien en estos días, debido a que es la etapa más linda del embarazo. Relájese y disfrute esta etapa.\n" +
                    "\n" +
                    "El abdomen no es muy grande, su bebé se mueve mucho y usted puede percibirlo. Además, los síntomas incómodos del primer trimestre ya han desaparecido.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/yoga-03.png", "", "A esta altura del embarazo se mueve constantemente, puede que lo haga hasta 50 veces por hora o más. Aunque usted sólo notará algunos, en especial cuando esté recostada o después de comer. Pesa alrededor de 300 gramos y mide cerca de 18 cm.\n" +
                    "\n" +
                    "Además de los movimientos que su bebé realiza con sus extremidades, se puede observar que también deglute líquido amniótico, fundamental para el desarrollo del tubo digestivo y de los pulmones, y realiza movimientos respiratorios o tiene hipo. La médula ósea empieza a producir glóbulos rojos, substituyendo progresivamente la función que realizaba hasta el momento el hígado y el bazo del feto.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/21%20hipo.png"),
            PregnancyWeek(22, "", """<b>Esta semana debe realizar:</b>
                <ul>
                <li><b>Ecografía semana 22 (scan fetal):</b> Esta ecografía tiene como principal objetivo detectar si el desarrollo anatómico del bebé es normal. Si bien la mayoría de los niños son sanos, algunos pueden tener malformaciones en su desarrollo, muchas de las cuales pueden ser evidentes en esta ecografía.  De acuerdo a sus antecedentes e historia clínica, su obstetra puede solicitarle una medición de la longitud del cuello del útero por ecografía transvaginal, lo cual permite estimar el riesgo de parto prematuro.</li>
                </ul>""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/ecograf(3).jpg", "", "Los síntomas como la constipación, la sensación de abdomen hinchado, el sangrado de encías o nariz pueden ser muy comunes a esta altura. En el caso del sangrado de encías, se sugiere consultar al odontólogo debido a que la salud bucal es muy importante en esta etapa.\n" +
                    "\n" +
                    "También puede que usted se sienta cansada y necesita hacer siestas reparadoras. No lo dude, si tiene la oportunidad, descanse todo lo que pueda.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M22%20-%20descanso.png", "", "En esta semana pesa 350 gramos aproximadamente y mide cerca de 20 cm. En su cara se pueden observar los párpados, que aún permanecen cerrados. Los labios pueden verse sin dificultad, muy bien delimitados y dentro de las encías comienzan a formarse los dientes.\n" +
                    "\n" +
                    "En el sistema nervioso central, el sistema límbico está desarrollándose hacia esta etapa. El sistema límbico será el encargado de los sentimientos, emociones y estados de ánimo. Los testículos de los niños ya tienen algunos espermatozoides y los ovarios de las niñas óvulos en su interior. El hígado ya comenzó a funcionar, aunque sus enzimas son aún inmaduras para metabolizar bilirrubina.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/22%20higado.png"),
            PregnancyWeek(23, "", "", "", "", "Es muy común que en esta semana haya sangrado de encías. Se sugiere consultar al odontólogo debido a que la salud bucal es muy importante en esta etapa.\n" +
                    "\n" +
                    "El segundo trimestre es el momento ideal para consultar al odontólogo.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M23%20-%20odontologo.png", "", "La piel del bebé se torna rojiza y arrugada, ya dejó de ser translúcida. Alrededor de esta semana comienza a acumularse en piel y ojos el pigmento que le dará el color definitivo, el cual lo alcanzará cerca del año de vida. Pesa cerca de 450 gramos en esta semana.\n" +
                    "\n" +
                    "Los huesos siguen su proceso de osificación, o sea pasando de cartílago a hueso. La calcificación se inicia en el centro de los huesos y progresa hacia los extremos.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/23%20piel.png"),
            PregnancyWeek(24, "", "", "", "", "El bebé se mueve constantemente y cada vez tiene más fuerza. Es muy frecuente que sus movimientos se sientan en forma intensa y todo el tiempo. Los dolores en la región lumbar también son muy frecuentes a partir de esta altura de la gestación.\n" +
                    "\n" +
                    "El útero ya ha sobrepasado el nivel del ombligo y es muy común que al estirarse la piel del abdomen se sienta picazón. Puede utilizar alguna crema humectante para disminuir esta sensación.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M24%20-%20crema.png", "", "En este momento del embarazo, los bebés tienen mucho espacio dentro del útero, por lo tanto es muy común que cambien de posición constantemente, incluso varias veces en el día. A esta altura, sus sentidos ya están desarrollados, esta semana pesa aproximadamente 700 gramos y  mide cerca de 22-24 cm.\n" +
                    "\n" +
                    "A partir de estas semana sucede algo muy relevante para el bebé: comienza a producir en los pulmones el surfactante pulmonar, una sustancia necesaria para que estos puedan hacer el intercambio de oxígeno al momento del nacimiento.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/24%20pulmones.png"),
            PregnancyWeek(25, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Inmunizaciones</b></li>
        <li><b>Vacuna triple bacteriana acelular</b></li>
        <li><b>Vacuna antigripal:</b> Si usted no tiene al día la vacuna triple bacteriana acelular, debe aplicársela.  Previene de la infección por tétanos durante procedimientos quirúrgicos (parto o cesárea), contra la difteria y la tos convulsa. De acuerdo a la estación del año, puede necesitar administrarse la vacuna antigripal.  Esta vacuna se puede aplicar en cualquier trimestre del embarazo.</li>
        <li><b>Laboratorios de rutina + PTOG (prueba de tolerancia oral a la glucosa):</b> Incluyen análisis de sangre para detección de anemia, serologías (para estudiar enfermedades como el HIV o Sífilis), análisis de orina para detectar infecciones urinarias asintómaticas.  La prueba de tolerancia oral a la glucosa (PTOG) sirve para detecta diabetes gestacional.</li>
        <li><b>El estudio consiste en::</b> Extraer sangre en ayuno. Luego, beber  un preparado con agua y 75 gr de glucosa. Dos horas más tarde, se toma una nueva muestra de sangre. Con esto se puede valorar que sucede con la glucemia (azúcar en la sangre) cuando usted está en ayuno y luego de consumir alimentos.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/controlemb.jpg", "", "Usted puede sentirse algo cansada, caminar cuesta cada vez más y los dolores de espalda están a la orden del día.\n" +
                    "\n" +
                    "Descanse todo lo que pueda e intente realizar alguna actividad que le permita elongar y fortalecer la espalda, como la actividad física en el agua o el yoga para embarazadas. Esto le ayudará con estas molestias.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/backpain-05.png", "", "A partir de estas semanas, los párpados del bebé, que ya estaban formados pero cerrados, se empiezan a abrir y ya tienen pestañas. Pesa cerca de 800 gramos.\n" +
                    "\n" +
                    "El bebé comienza a escuchar los sonidos, sobre todo los que provienen del cuerpo de la mamá y los propios, como sus movimientos que agitan el líquido amniótico. También son capaces de percibir sonidos, música y voces provenientes del exterior.  Algunos trabajos refieren que los bebés, al nacimiento, pueden reconocer las voces de su madre, padre y algunas palabras que han escuchado durante el embarazo.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/25%20oido%20voces.png"),
            PregnancyWeek(26, "", "", "", "", "Puede que usted tenga cambios en el tránsito intestinal.  El crecimiento del útero ha sobrepasado el ombligo y sus intestinos tienen poco espacio. Esto puede producir tránsito lento y constipación. Una dieta rica en fibras le ayudará a sobrellevar estas molestias.\n" +
                    "\n" +
                    "La gran presión que ejerce el útero y el bebé en los grandes vasos del abdomen (vena cava) pueden provocar varices en las piernas y hemorroides. ", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M26%20-%20panza.png", "", "Durante el día, tendrá periodos de sueño y periodos de vigilia. Usted notará que la gran parte del tiempo está dormido pero, al despertarse, los movimientos serán muy evidentes. Es capaz de deglutir cerca de medio litro de líquido amniótico y se encuentra pesando cerca de 900 gramos y de la cabeza hasta las nalgas mide unos 25 cm.\n" +
                    "\n" +
                    "Ya ha desarrollado sus reflejos, uno de los más importantes es el reflejo de Moro, que puede observarse cuando el bebé estira sus brazos o piernas en caso de que haya algún sonido muy fuerte o algún estímulo importante en el abdomen. Aparecen progresivamente los movimientos respiratorios y el hipo.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/26%20brazos%20piernas.png"),
            PregnancyWeek(27, "", "", "", "", "Es bastante frecuente que a partir de ahora comiencen a hincharse sus pies. Esto se debe a retención de líquidos.\n" +
                    "\n" +
                    "Muchas mujeres embarazadas perciben las contracciones de Braxton Hicks. Si usted siente contracciones a esta altura, lo más probable es que sea normal. Estas contracciones se caracterizan por ser irregulares, aisladas, de corta duración y baja intensidad. Si las contracciones que usted percibe tienen otras características, es mejor que consulte a su médico.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M27%20-%20pies.png", "", "En esta semana ya pesa cerca de un kilogramo.\n" +
                    "\n" +
                    "El hipo y los movimientos respiratorios se hacen cada vez más frecuente a esta altura, debido a que el bebé comienza a prepararse para el nacimiento, ejercitando su diafragma y los músculos respiratorios.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/27%20pulmones.png"),
            PregnancyWeek(28, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Ecografía:</b> Esta ecografía sirve principalmente para evaluar el crecimiento y el bienestar del bebé.</li>
        <li><b>Aplicación de inmunoglobulina anti D en pacientes Rh negativas:</b> Si usted es Rh negativa y el padre del bebé es Rh positivo, su bebé puede ser Rh positivo y producirse una enfermedad llamada Isoinmunización Rh. Para prevenir esta enfermedad, su médico le hará una prueba en sangre (prueba de coombs indirecta).  Si esta pruega es negativa, usted deberá aplicarse una inyección (inmunoglobulina anti D) para evitar complicaciones en futuros embarazos.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/ecograf(1).jpg", "", "Los síntomas más frecuentes en este trimestre tienen relación con el aumento del tamaño de su abdomen.\n" +
                    "\n" +
                    "Usted puede sentir dolores de espalda, muchas ganas de orinar, hinchazón de pies y manos, falta de aire al caminar y es muy probable que comience a dormir mal durante las noches.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M28%20-%20insomio.png", "", "¡Comenzó el tercer trimestre!\n" +
                    "\n" +
                    "Una de las características de esta etapa es el rápido crecimiento fetal, sobre todo de peso.  Esto se debe a que el bebé continúa acumulando grasa debajo de la piel. En esta semana su bebé pesa 1100 - 1200 gramos. Cada vez se mueve más y con más fuerza.\n" +
                    "\n" +
                    "El sistema nervioso central del feto continúa desarrollándose, el cerebro comienza a tener surcos en la corteza. Existen estudios que indican que el bebé es capaz de identificar la voz de su mamá y algunos sonidos o melodías que haya escuchado durante el embarazo, por lo que se cree que la memoria a largo plazo comienza antes del nacimiento.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/audio-01.png"),
            PregnancyWeek(29, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Ecografía:</b> Esta ecografía sirve principalmente para evaluar el crecimiento y el bienestar del bebé.</li>
        <li><b>Aplicación de inmunoglobulina anti D en pacientes Rh negativas:</b> Si usted es Rh negativa y el padre del bebé es Rh positivo, su bebé puede ser Rh positivo y producirse una enfermedad llamada Isoinmunización Rh. Para prevenir esta enfermedad, su médico le hará una prueba en sangre (prueba de coombs indirecta).  Si esta pruega es negativa, usted deberá aplicarse una inyección (inmunoglobulina anti D) para evitar complicaciones en futuros embarazos.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/ecograf(3).jpg", "", "Su bebé aumenta de peso a gran velocidad y es probable que usted también aumente. Un poco más adelante, probablemente su peso se estabilice pero es muy común que aumente entre 3-5 kilos.\n" +
                    "\n" +
                    "Cada vez puede ser más evidente la hinchazón en pies y también en manos. En algunas mujeres la hinchazón en las manos produce dolor en las muñecas similar a una corriente eléctrica. Esto se debe a la retención de líquidos y suele mejorar cuando nace el bebé. Las contracciones de Braxton Hicks puede que sean más intensas y más seguidas. Ante cualquier duda, consulte al médico.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M29%20-%20aun%20mas%20panza.png", "", "En esta semana el bebé pesa cerca de un kilo y medio. Sus párpados ya se abren y cierran pero no puede experimentar la porque dentro del útero no hay luz. La piel del bebé pass de ser rojiza y arrugada a estar rosada y lisa, cubierta por la sustancia oleosa llamada unto sebáceo.\n" +
                    "\n" +
                    "Sus huesos continúan osificándose, aunque ya poseen su forma definitiva. La cabeza continúa siendo un poco mayor que el resto del cuerpo. Los pulmones del bebé continúan su proceso de maduración para lograr un intercambio de oxígeno efectivo al momento del nacimiento. Si su bebé es un varón, los testículos están en proceso de descender desde el abdomen hacia el escroto.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/29%20panza.png"),
            PregnancyWeek(30, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Ecografía:</b> Esta ecografía sirve principalmente para evaluar el crecimiento y el bienestar del bebé.</li>
        <li><b>Aplicación de inmunoglobulina anti D en pacientes Rh negativas:</b> Si usted es Rh negativa y el padre del bebé es Rh positivo, su bebé puede ser Rh positivo y producirse una enfermedad llamada Isoinmunización Rh. Para prevenir esta enfermedad, su médico le hará una prueba en sangre (prueba de coombs indirecta).  Si esta pruega es negativa, usted deberá aplicarse una inyección (inmunoglobulina anti D) para evitar complicaciones en futuros embarazos.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/blood.jpg", "", "Su bebé cada día estará más grande y sus movimientos podrán sentirse en todo el abdomen.\n" +
                    "\n" +
                    "La pelvis comienza a expandirse para darle lugar a la salida del bebé. Esto se debe a una hormona llamada relaxina que “afloja” las articulaciones.  Usted puede sentir dolor en el pubis y las caderas.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M30%20-%20patadas.png", "", "Algo característico de esta etapa es que el feto comienza a ubicarse en la posición definitiva que tendrá al nacer, que en la mayoría de los casos es con la cabeza hacia abajo (cefálica). Igualmente algunos bebés pueden cambiar de posición a último momento.\n" +
                    "\n" +
                    "La mayoría de los órganos fetales ya comienzan a funcionar. Por ejemplo el tubo digestivo por el cual atraviesa el líquido amniótico que el bebé deglute. La audición también ha madurado y ya comienza a escuchar mejor los sonidos graves  como el latido cardíaco materno. En esta semana pesa un poco más de 1.500 gramos (1,5 kilos).", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/30%20posicion.png"),
            PregnancyWeek(31, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Ecografía:</b> Esta ecografía sirve principalmente para evaluar el crecimiento y el bienestar del bebé.</li>
        <li><b>Aplicación de inmunoglobulina anti D en pacientes Rh negativas:</b> Si usted es Rh negativa y el padre del bebé es Rh positivo, su bebé puede ser Rh positivo y producirse una enfermedad llamada Isoinmunización Rh. Para prevenir esta enfermedad, su médico le hará una prueba en sangre (prueba de coombs indirecta).  Si esta pruega es negativa, usted deberá aplicarse una inyección (inmunoglobulina anti D) para evitar complicaciones en futuros embarazos.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/blood(1).jpg", "", "Así como su bebé crece rápidamente, puede que usted aumente de peso de la misma manera. Algunas mujeres pueden tener secreción por los pezones. Este líquido espeso y algo transparente se llama calostro y es el primer alimento del bebé.\n" +
                    "\n" +
                    "Los síntomas de falta de aire, acidez o sensación de digestión lenta son cada vez más frecuentes debido al tamaño de su abdomen y la presión que el útero ejerce.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M31%20-%20bigger.png", "", "Su preparación para el nacimiento continúa. Gracias a la acumulación de grasa subcutánea la piel aparece más rosada y la cara del bebé se observa más redondeada. Sus órganos, ya completamente formados, están madurando y su peso aumenta día a día (esta semana estará en 1700 gramos aprox.)  \n" +
                    "\n" +
                    "Los pulmones del bebé están cada vez más maduros. Los riñones fetales son capaces de producir cerca de medio litro de orina.  Recuerde que ya a esta altura el líquido amniótico fetal depende casi en su totalidad de la producción de orina del bebé.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/31%20organos.png"),
            PregnancyWeek(32, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Ecografía:</b> Esta ecografía sirve principalmente para evaluar el crecimiento y el bienestar del bebé.</li>
        <li><b>Aplicación de inmunoglobulina anti D en pacientes Rh negativas:</b> Si usted es Rh negativa y el padre del bebé es Rh positivo, su bebé puede ser Rh positivo y producirse una enfermedad llamada Isoinmunización Rh. Para prevenir esta enfermedad, su médico le hará una prueba en sangre (prueba de coombs indirecta).  Si esta pruega es negativa, usted deberá aplicarse una inyección (inmunoglobulina anti D) para evitar complicaciones en futuros embarazos.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/blood(1).jpg", "", "Usted se irá sintiendo cada día más cansada. Caminar se hará dificultoso, dormir por las noches también. Intente descansar todo lo que pueda cuando pueda.  Para mejorar la calidad del sueño, intente descansar de costado izquierdo o semisentada con varias almohadas.\n" +
                    "\n" +
                    "Los despertares para orinar o causados por los movimientos del bebé mientras usted duerme, harán que su descanso no sea tan placentero.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M32%20-%20sleep.png", "", "Al observarlo, su aspecto es prácticamente igual al de un bebé recién nacido pero con menos peso (esta semana se encuentra pesando cerca de 1900 gramos). Tiene pelo, cejas y las uñas alcanzan la punta de los dedos. La piel es rosada y lisa y está cubierta por una gran cantidad de unto sebáceo. Generalmente, el feto ya se encuentra en la posición en la que va a nacer y es raro que cambien.\n" +
                    "\n" +
                    "Todos los órganos fetales están madurando, sobre todo el aparato respiratorio,  y lo seguirán haciendo hasta el nacimiento.  Si un bebé nace a esta altura, tiene altas probabilidades de supervivencia, pero sigue siendo prematuro. El término se alcanza en la semana 37-38.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/32%20carita%20pelo.png"),
            PregnancyWeek(33, "", "", "", "", "Las contracciones habituales de esta etapa son cada vez más fuertes.  Es importante que usted controle que las mismas no sean más de 3 contracciones en 10 minutos, si esto sucede, es mejor que consulte a su médico o a la guardia.\n" +
                    "\n" +
                    "El calostro (secreción por pezón) puede continuar saliendo hasta el nacimiento del bebé y luego del parto, durante los primeros días.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M33%20-%20contracciones.png", "", "Ya superó los 2000 gramos (2 kilos) de peso y mide aproximadamente 44 cm de cabeza a pies. A lo largo de estas últimas semanas, el cerebro ha continuado su maduración gracias al aumento del número de neuronas y de las conexiones entre ellas, un proceso clave en la formación y maduración del cerebro.\n" +
                    "\n" +
                    "Tiene capacidad de soñar, en esta etapa es posible observar los Movimientos Oculares Rápidos que se producen durante una etapa del sueño.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/33%20-%20sue%C3%B1o.png"),
            PregnancyWeek(34, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Ecografía:</b> Esta ecografía sirve principalmente para evaluar el crecimiento y el bienestar del bebé.</li>
        <li><b>Laboratorio de rutina + Cultivo de estreptococo beta hemolítico:</b> Esta bacteria es flora habitual de la zona anal y vaginal de algunas mujeres.  Si el cultivo le dá positivo, durante el trabajo de parto usted recibirá un antibiótico para evitar que el bebé se infecte al pasar por el canal de parto.</li>
        <li><b>Evaluación prequirúrgica:</b> Esta evaluación es realizada por un anestesiólogo y un médico clínico con el fin de evitar complicaciones durante el parto o la cesárea.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/embyenf.jpg", "", "Cansancio, sensación de falta de aire, mal dormir son los síntomas más comunes en esta etapa. La hinchazón de manos y pies puede ser más notoria. Si usted observa que repentinamente se incrementa esta hinchazón es conveniente que consulte a su obstetra.\n" +
                    "\n" +
                    "Es común presentar hemorroides o varices en la vulva. Generalmente, esto suele mejorar luego del parto. Las contracciones permanecen y se hacen cada vez más intensas y frecuentes.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M34%20mas%20grande.png", "", "Continúa acumulando grasa, su piel es cada vez más tersa y su aspecto cada vez más parecido al de un recién nacido. El hipo es un movimiento que la madre percibe como rítmico, rápido y de duración variable, generalmente unos minutos.  A esta altura, pueden tener hipo varias veces al día. Ya está pesando 2300 gramos aproximadamente. Responde a diversos estímulos provenientes del exterior y son muy claros sus periodos de sueño y vigilia.\n" +
                    "\n" +
                    "Los pulmones han madurado casi por completo. Si se produjera una amenaza de parto prematuro, se requiere administrar corticoides a la madre para completar el proceso de maduración de los pulmones y así evitar complicaciones.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/34%20-%20cerebro.png"),
            PregnancyWeek(35, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Ecografía:</b> Esta ecografía sirve principalmente para evaluar el crecimiento y el bienestar del bebé.</li>
        <li><b>Laboratorio de rutina + Cultivo de estreptococo beta hemolítico:</b> Esta bacteria es flora habitual de la zona anal y vaginal de algunas mujeres.  Si el cultivo le dá positivo, durante el trabajo de parto usted recibirá un antibiótico para evitar que el bebé se infecte al pasar por el canal de parto.</li>
        <li><b>Evaluación prequirúrgica:</b> Esta evaluación es realizada por un anestesiólogo y un médico clínico con el fin de evitar complicaciones durante el parto o la cesárea.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/embyenf(1).jpg", "", "El útero llega prácticamente por debajo de las costillas.  Algunas mujeres pueden observar la aparición de estrías debido al estiramiento de la piel. Esto dependerá de la predisposición de cada mujer. También es común observar el ombligo que sobresale del abdomen, por la presión que ejerce el útero desde el interior.\n" +
                    "\n" +
                    "Si su bebé se encuentra con la cabeza hacia abajo, es frecuente que comience a sentir la cabeza en la pelvis y esto puede provocar puntadas en la articulación del pubis. Todas estas sensaciones avisan que su bebé se está preparando para el nacimiento.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M35%20-%20posicion.png", "", "En las últimas semanas del embarazo, la madre le pasa al bebé sus propios anticuerpos, protegiéndolo hasta después del nacimiento, cuando se le administren las primeras vacunas. Ya está pesando 2500 gramos y mide unos 46 cm de cabeza a pies.\n" +
                    "\n" +
                    "Probablemente sus pulmones ya estén maduros en caso de desencadenarse el parto.  Sin embargo, algunos estudios avalan la administración de corticoides para evitar complicaciones respiratorias en esta semana.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/35%20-%20remedios.png"),
            PregnancyWeek(36, "", "", "", "", "", "", "", "Ya está pesando alrededor de 2.700 gramos y mide cerca de 47 cm. Este aumento de peso y tamaño hace que el espacio que tiene dentro del útero sea menor, por lo tanto los movimientos también serán más suaves y seguramente se perciban menos.\n" +
                    "\n" +
                    "Esta es la última semana en la que se considera un feto prematuro, ya que desde la semana 37 a la 40, se considera un bebé a término.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/36%20-%20bordes.png"),
            PregnancyWeek(37, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Examen físico:</b> Su médico evaluará la necesidad de realizar un tacto vaginal para valorar las condiciones del cuello uterino.</li>
        <li><b>Monitoreos fetales:</b> El monitoreo fetal es un estudio en el cual se registra la frecuencia cardíaca fetal y las contracciones uterinas. Cuando el monitoreo es reactivo, en la mayoría de los casos esto significa que su bebé se encuentra saludable.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/embyenf(1).jpg", "", "Usted ha llegado a la recta final de su embarazo.  ¡Felicitaciones!\n" +
                    "\n" +
                    "Tómese su tiempo para preparar todo lo que necesita llevar al hospital tanto para su bebé como para usted.\n" +
                    "\n" +
                    "A partir de esta semana, los controles serán más seguidos y usted realizará un monitoreo de los latidos de su bebé en forma semanal. Es bueno que conozca cuáles son los signos que le avisarán el inicio del trabajo de parto.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M37%20-%20recta%20final.png", "", "Ya se considera que está a término, pesa casi 3 kilos aproximadamente y mide unos 48 cm. No aumenta demasiado de peso a partir de esta semana pero si continúa acumulando grasa por debajo de la piel, lo que le permitirá al momento de nacer, regular mejor la temperatura corporal.\n" +
                    "\n" +
                    "La mayoría de los bebés se encuentran en posición cefálica, es decir con la cabeza hacia la pelvis. Sólo un pequeño porcentaje de bebés se colocan con la cola hacia abajo o atravesados.  En estos últimos casos, se programa una cesárea entre las 39-40 semanas para evitar complicaciones al momento del nacimiento.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/37%20-%20piel%20cubierta.png"),
            PregnancyWeek(38, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Examen físico:</b> Su médico evaluará la necesidad de realizar un tacto vaginal para valorar las condiciones del cuello uterino.</li>
        <li><b>Monitoreos fetales:</b> El monitoreo fetal es un estudio en el cual se registra la frecuencia cardíaca fetal y las contracciones uterinas. Cuando el monitoreo es reactivo, en la mayoría de los casos esto significa que su bebé se encuentra saludable.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/controlemb(1).jpg", "", "Los controles a esta altura son más seguidos y usted realizará un monitoreo de los latidos de su bebé en forma semanal.\n" +
                    "\n" +
                    "Es bueno que conozca cuáles son los signos que le avisarán el inicio del trabajo de parto.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M38%20-%20final.png", "", "Su bebé ya está listo para nacer.  Se encuentra pesando más de 3000 gramos y mide unos 48 cm de cabeza a pies. Ha desarrollado el tono muscular y los miembros superiores e inferiores se encuentran flexionados. La grasa subcutánea aumenta y la piel es lisa y suave, blanquecina o rosada.\n" +
                    "\n" +
                    "El cuerpo del bebé se encuentra cubierto por lanugo y unto sebáceo, los cuales de a poco van desapareciendo. El cabello es más largo y grueso y las uñas de las manos sobrepasan la punta de los dedos.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/38%20-%20almost%20ready(1).png"),
            PregnancyWeek(39, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Examen físico:</b> Su médico evaluará la necesidad de realizar un tacto vaginal para valorar las condiciones del cuello uterino.</li>
        <li><b>Monitoreos fetales:</b> El monitoreo fetal es un estudio en el cual se registra la frecuencia cardíaca fetal y las contracciones uterinas. Cuando el monitoreo es reactivo, en la mayoría de los casos esto significa que su bebé se encuentra saludable.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/controlemb(3).jpg", "", "Los controles a esta altura son más seguidos y usted realizará un monitoreo de los latidos de su bebé en forma semanal.\n" +
                    "\n" +
                    "Es bueno que conozca cuáles son los signos que le avisarán el inicio del trabajo de parto.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M39%20-%20final.png", "", "Sigue creciendo y aumentando principalmente la capa de grasa que se encuentra por debajo de la piel. Esta grasa le permitirá regular correctamente su temperatura corporal una vez que haya nacido.\n" +
                    "\n" +
                    "Los pulmones y el cerebro son las estructuras fetales que en este momento de la gestación continúan madurando.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/bolso-03.png"),
            PregnancyWeek(40, "", """
    <b>Esta semana debe realizar:</b>
    <ul>
        <li><b>Examen físico:</b> Su médico evaluará la necesidad de realizar un tacto vaginal para valorar las condiciones del cuello uterino.</li>
        <li><b>Monitoreos fetales:</b> El monitoreo fetal es un estudio en el cual se registra la frecuencia cardíaca fetal y las contracciones uterinas. Cuando el monitoreo es reactivo, en la mayoría de los casos esto significa que su bebé se encuentra saludable.</li>
    </ul>
""", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/controlemb(3).jpg", "", "Los controles a esta altura son más seguidos y usted realizará un monitoreo de los latidos de su bebé en forma semanal.\n" +
                    "\n" +
                    "Es bueno que conozca cuáles son los signos que le avisarán el inicio del trabajo de parto.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/M40%20-%20final.png", "", "Las medidas del bebé están entre los 48 y 50 cm de la cabeza a los pies y el peso se encuentra alrededor de los 3.400 gramos. El unto sebáceo ha desaparecido casi por completo aunque pueden quedar algunos restos en los pliegues.\n" +
                    "\n" +
                    "Usted  debe seguir notando las patadas del bebé, aunque es probable que se perciban menos debido a que el bebé cada vez tiene menos espacio para moverse. En caso de no sentir ningún movimiento durante una hora usted puede estimularlo desde la superficie del abdomen o comiendo algo dulce. Si con el estímulo el bebé continúa sin moverse, es necesario que consulte.", "https://hiba.hospitalitaliano.org.ar/archivos/noticias_archivos/53/archivos/40%20-%20ready.png")
        )
    }
}